databases.resort_vdb.folder.1\ -\ dataconnection.folder.2\ -\ baseviews.views.jdbc.bv_customer_amenities_booking.CATALOGNAME=resort360
databases.resort_vdb.folder.1\ -\ dataconnection.folder.2\ -\ baseviews.views.jdbc.bv_customer_amenities_booking.SCHEMANAME=dbo
