databases.resort_vdb.folder.1\ -\ dataconnection.folder.2\ -\ baseviews.views.jdbc.bv_payment.CATALOGNAME=resort360
databases.resort_vdb.folder.1\ -\ dataconnection.folder.2\ -\ baseviews.views.jdbc.bv_payment.SCHEMANAME=dbo
