databases.resort_vdb.folder.1\ -\ dataconnection.folder.2\ -\ baseviews.views.jdbc.bv_room_category.CATALOGNAME=resort360
databases.resort_vdb.folder.1\ -\ dataconnection.folder.2\ -\ baseviews.views.jdbc.bv_room_category.SCHEMANAME=dbo
