databases.resort360.folder.1\ -\ dataconnection.folder.1\ -\ data\ sources.views.jdbc.bv_users.CATALOGNAME=resort360
databases.resort360.folder.1\ -\ dataconnection.folder.1\ -\ data\ sources.views.jdbc.bv_users.SCHEMANAME=dbo
