databases.resort360.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_booking_type.CATALOGNAME=resort360
databases.resort360.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_booking_type.SCHEMANAME=dbo
