databases.resort360.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_product_sub_category.CATALOGNAME=resort360
databases.resort360.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_product_sub_category.SCHEMANAME=dbo
