databases.resort360.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_tour_operator_transaction.CATALOGNAME=resort360
databases.resort360.folder.1\ -\ dataconnection.folder.2\ -\ base\ views.views.jdbc.bv_tour_operator_transaction.SCHEMANAME=dbo
